apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: waves
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3dhdmVzX3VzZXI6d2F2ZXNfcGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZS53YXZlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3dhdmVzX211c2lj
  SECRET_KEY: MTVhNWIyN2VkNjU2MzVkZjlmMDExMWM3NGI4MjhmMDE2NjFmYmYxZDMzODhiMzdjMjk4OGY1Y2U4NTlkMDdmMw==
