apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  namespace: waves
spec:
  accessModes:
    - ReadWriteMany # Minikube supports ReadWriteMany
  storageClassName: standard # Minikube default storage class
  resources:
    requests:
      storage: 20Gi
