apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  namespace: waves
spec:
  accessModes:
    - ReadWriteOnce # Single node access (GCP standard-rwo requirement)
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 20Gi
