apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: waves
type: Opaque
data:
  POSTGRES_USER: d2F2ZXNfdXNlcg==
  POSTGRES_PASSWORD: d2F2ZXNfcGFzc3dvcmQ=
  POSTGRES_DB: d2F2ZXNfbXVzaWM=
